// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSENmoReNdWayj0_AMTkAP16Zhbu7kGmk',
    appId: '1:1096357836745:web:5af695c12b379755099a18',
    messagingSenderId: '1096357836745',
    projectId: 'easy-coupon-5ce03',
    authDomain: 'easy-coupon-5ce03.firebaseapp.com',
    storageBucket: 'easy-coupon-5ce03.appspot.com',
    measurementId: 'G-3WQ9DFYCBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYYUcrxlXnnD2AkpNOOczxjrXlbOLOp5w',
    appId: '1:1096357836745:android:e43f45572630a7cd099a18',
    messagingSenderId: '1096357836745',
    projectId: 'easy-coupon-5ce03',
    storageBucket: 'easy-coupon-5ce03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAgpJViD47RPYW9wbAJO7jlE5nWYr__aI',
    appId: '1:1096357836745:ios:a55c47bd49e1c3d2099a18',
    messagingSenderId: '1096357836745',
    projectId: 'easy-coupon-5ce03',
    storageBucket: 'easy-coupon-5ce03.appspot.com',
    iosBundleId: 'com.example.easyCoupon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAgpJViD47RPYW9wbAJO7jlE5nWYr__aI',
    appId: '1:1096357836745:ios:a55c47bd49e1c3d2099a18',
    messagingSenderId: '1096357836745',
    projectId: 'easy-coupon-5ce03',
    storageBucket: 'easy-coupon-5ce03.appspot.com',
    iosBundleId: 'com.example.easyCoupon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSENmoReNdWayj0_AMTkAP16Zhbu7kGmk',
    appId: '1:1096357836745:web:699440bc8b629cfb099a18',
    messagingSenderId: '1096357836745',
    projectId: 'easy-coupon-5ce03',
    authDomain: 'easy-coupon-5ce03.firebaseapp.com',
    storageBucket: 'easy-coupon-5ce03.appspot.com',
    measurementId: 'G-ES11ZLY1F6',
  );
}
